### ISSUE TITLE
DVAE backup link 

### ISSUE THREAD

**Issue by Ryu1845** [152334H/DL-Art-School#20]
> this will definitely be taken down at some point; open an issue with a backup link and i'll replace it

https://huggingface.co/Gatozu35/tortoise-tts/resolve/main/dvae.pth

**Comment by 152334H** [comment]
updated the link in install instructions + colab, added hashsum as well

**Comment by MEZTech-LLC** [comment]
I realize this is closed, but I'm curious - is this DVAE the same as what jbetker originally trained with tortoise? Or was it trained separately, in which case CLVP/CVVP should be used from the Gatozu35 files?

**Comment by Ryu1845** [comment]
The DVAE is from jbetker yes.

**Comment by MEZTech-LLC** [comment]
So jbetker had originally uploaded the trained cvae and later removed it? (Presumably to reduce liability -- https://github.com/neonbjb/tortoise-tts/issues/177)?

> Hi There, This model is extremely potent when fine-tuned. It can be easily used to make deep-fake voiceovers of people. I'm sure you've heard the Joe Rogan and Steve Jobs podcast - that was Tortoise. Withholding the VQVAE which is required to perform that fine-tuning is my way of de-weaponizing it, to an extent.
> 
> > Eventually someone is just going to make their own training scripts for this and publish it on somewhere like Google colab or something.
> 
> You're right. It won't be me that releases it, though. Even if this wasn't a question of morals (which it absolutely is), I do not want to be legally responsible for the misuse of this model.

**Comment by Ryu1845** [comment]
Yes

**Comment by MEZTech-LLC** [comment]
Got it - well big thank you for providing access to the trained DVAE!
