### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rikabi89** [152334H/DL-Art-School#28]
`3-02-21 09:05:37.187 - INFO: [epoch:  0, iter:       0, lr:(1.000e-05,1.000e-05,)] step: 0.0000e+00 samples: 8.0000e+00 megasamples: 8.0000e-06 iteration_rate: 3.6583e-01 loss_text_ce: 4.2470e+00 loss_mel_ce: 2.9319e+00 loss_gpt_total: 2.9744e+00 grad_scaler_scale: 1.0000e+00 learning_rate_gpt_0: 1.0000e-05 learning_rate_gpt_1: 1.0000e-05 total_samples_loaded: 8.0000e+00 percent_skipped_samples: 1.1111e-01 percent_conditioning_is_self: 8.8889e-01 gpt_conditioning_encoder: 4.6525e+00 gpt_gpt: 4.9838e+00 gpt_heads: 5.3694e+00
23-02-21 09:05:37.187 - INFO: Saving models and training states.
  0%|                                                                                            | 0/1 [00:08<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ H:\DL-Art-School\codes\train.py:381 in <module>                                                  │
│                                                                                                  │
│   378 │   │   torch.cuda.set_device(torch.distributed.get_rank())                                │
│   379 │                                                                                          │
│   380 │   trainer.init(args.opt, opt, args.launcher)                                             │
│ ❱ 381 │   trainer.do_training()                                                                  │
│   382                                                                                            │
│                                                                                                  │
│ H:\DL-Art-School\codes\train.py:336 in do_training                                               │
│                                                                                                  │
│   333 │   │   │                                                                                  │
│   334 │   │   │   _t = time()                                                                    │
│   335 │   │   │   for train_data in tq_ldr:                                                      │
│ ❱ 336 │   │   │   │   self.do_step(train_data)                                                   │
│   337 │                                                                                          │
│   338 │   def create_training_generator(self, index):                                            │
│   339 │   │   self.logger.info('Start training from epoch: {:d}, iter: {:d}'.format(self.start   │
│                                                                                                  │
│ H:\DL-Art-School\codes\train.py:263 in do_step                                                   │
│                                                                                                  │
│   260 │   │   │   │   │   self.logger.info('Saving models and training states.')                 │
│   261 │   │   │   │   else:                                                                      │
│   262 │   │   │   │   │   self.logger.info('Saving model.')                                      │
│ ❱ 263 │   │   │   │   if opt['upgrades']['number_of_checkpoints_to_save'] > 0:                   │
│   264 │   │   │   │   │   self.logger.info(                                                      │
│   265 │   │   │   │   │   │   f"Leaving only {opt['upgrades']['number_of_checkpoints_to_save']   │
│   266 │   │   │   │   │   )                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable`

![image](https://user-images.githubusercontent.com/85737703/220300414-ef33e28d-1b84-4071-9c12-de180fa84928.png)

![image](https://user-images.githubusercontent.com/85737703/220300143-bf664071-e43d-432c-9dcf-15604a3099fa.png)

Using the latest version of DLAS but seem to get this error on a small dataset. I used the previous version with little issues. Not sure what this means?

**Comment by devilismyfriend** [comment]
You're seemingly not using the  latest version as you're missing the logo (there were other changes there as well)

**Comment by rikabi89** [comment]
Sorry I took a screenshot of the wrong version. That's the old one but I have the new installed with the logo.

**Comment by devilismyfriend** [comment]
I see, I think I found the issue, pull down the new commit and start training again.

**Comment by rikabi89** [comment]
Great stuff looks like it training now!

Just a side question, I was using your transcribing tool and experimenting with fine-training with not too much success. Thank you for your efforts. But is it normal from most of the wavs to end up in validation txt and only few as training?

**Comment by devilismyfriend** [comment]
it should be determined by the valid_split in the config, what do you have it set to?

it's not normal for most wavs to end up as validation

**Comment by rikabi89** [comment]
> it should be determined by the valid_split in the config, what do you have it set to?
> 
> it's not normal for most wavs to end up as validation

`hf_token = *******************
whisper_model = openai/whisper-large-v2
device = cuda
diaization_model = pyannote/speaker-diarization
segmentation_model = pyannote/segmentation
valid_ratio = 0.2
seg_onset = 0.6
seg_offset = 0.4
seg_min_duration = 2.0
seg_min_duration_off = 0.0

`
I just have default settings. What should I change it to?
