### ISSUE TITLE
Please remove .idea folders from repository

### ISSUE THREAD

**Issue by 8tm** [152334H/DL-Art-School#30]
Hi,
it's nice that you are using Pycharm (I'm using it too) but your setting are in conflict with mine and every time I want to create some change (like now for yesterday merged changes related with disabling states generation and my changes related with saving only X last checkpoints and x last states) I have to remove your settings, add my own and reload Pycharm virtual environment settings, or I need to fix conflicts. It's very annoying.

It would be nice to remove `.idea/` folders from repository (there are two - in main folder and in codes subfolder) and add it to file `.gitignore` so every one of us could use their own settings (and this folder shouldn't be in repository at all because it's not related with project, so you know... :) ).

I can create pull request for if it it helps.

Thank you for your help :)

**Comment by 152334H** [comment]
I'm not using pycharm at all. I have never poked the `.idea/` folder in my life. I have no idea what the pycharm setup is like, or what it does. 

Feel free to add a pull request to completely eradicate both pycharm folders. I would like a public PR to point to in the unlikely event that someone else is using the `.idea` folders.

**Comment by 8tm** [comment]
PR ready: https://github.com/152334H/DL-Art-School/pull/31
