### ISSUE TITLE
Pip subprocess error

### ISSUE THREAD

**Issue by Matiusauce** [152334H/DL-Art-School#39]
Getting an error on Windows when running Startup DLAS. The installer proceeds after and says completed but then I am missing many dependencies when I try to run "Start DLAS". I can get past them by manually installing each, getting into the UI and starting training but I eventually get an error where it cannot import FixedPositionalEmbedding from x_transformers.

Error is:

```
Collecting bitsandbytes
  Using cached bitsandbytes-0.37.0-py3-none-any.whl (76.3 MB)
Collecting lion-pytorch==0.0.7
  Using cached lion_pytorch-0.0.7-py3-none-any.whl (4.3 kB)

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement triton==2.0.0a2 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0a2

failed

CondaEnvException: Pip failed

Fixing Tensorboard...
```

**Comment by 152334H** [comment]
I suspect this is caused by the pip installation command not searching for pre-releases. You can solve this immediately by executing `pip install --pre -U triton` **within the conda env**, but ideally a long term solution would address it.

**Comment by Matiusauce** [comment]
Seems like it might be an issue with triton as documented on their GitHub [here](https://github.com/openai/triton/issues/122)

**Comment by devilismyfriend** [comment]
It's not possible to install Triton from pip on Windows, I added it to the post install @152334H

**Comment by Matiusauce** [comment]
Can confirm triton does actually install via the post install script from hugging face so the initial error can be ignored. My issue must be something else.

Will try to figure it out tomorrow.

Closing this one.
