### ISSUE TITLE
Batch Size for 24 GB VRAM

### ISSUE THREAD

**Issue by Snowad14** [152334H/DL-Art-School#42]
What batch size do you use on 24 GB of vram?

**Comment by 152334H** [comment]
highest I've used is 128, which leaves lots of vram to spare in my experience

Plausibly this could be a lot higher if your wav files are very long

**Comment by Snowad14** [comment]
Do you use gradient checkpointing?

**Comment by 152334H** [comment]
yes I see no reason to disable it
