### ISSUE TITLE
Triton in Requirements File Doesnt Work

### ISSUE THREAD

**Issue by ManyStrongWords** [152334H/DL-Art-School#46]
Removing Triton from the end of the 'requirements.laxed_edited.txt' file 
and manually installing triton using 
pip install -U --pre triton
allows the program to function

**Comment by 152334H** [comment]
https://github.com/152334H/DL-Art-School/commit/44247f7a674f348ae78f70ff4352f39a53d380d6

it's only needed for lion, which is not functioning by default anyway, so i'll remove it
