### ISSUE TITLE
ModuleNotFoundError: No module named 'tortoise'

### ISSUE THREAD

**Issue by testusersample1** [152334H/DL-Art-School#54]
I get that error when trying to create voice/text in the playground, when I click generate nothing happens and that error is in the cli. I've already deleted the tortoise-tts-fast folder so it could be installed again, didn't fix it.
![e27d6b831a30500886b0e1b049bd8a62](https://user-images.githubusercontent.com/127815758/224887318-9da40f92-f187-4c2d-a52b-94c26cdf8e27.png)

EDIT:

could be related, this is during the install of tortoise 

```
  × Running setup.py install for pesq did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\setuptools\__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      running install
      C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pesq
      copying pesq\_pesq.py -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\__init__.py -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\cypesq.pyx -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\dsp.h -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesq.h -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesqio.h -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesqmain.h -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesqpar.h -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\dsp.c -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesqdsp.c -> build\lib.win-amd64-cpython-310\pesq
      copying pesq\pesqmod.c -> build\lib.win-amd64-cpython-310\pesq
      running build_ext
      skipping 'pesq\cypesq.c' Cython extension (up-to-date)
      building 'cypesq' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pesq

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by testusersample1** [comment]
So after installing the microsoft C++ Build Tools it seems to have fixed that issue, however there's now another error

`Environment name is set as "DLAS" as per environment.yaml
anaconda3/miniconda3 detected in C:\Users\Dominik\anaconda3
Starting conda environment "DLAS" from C:\Users\Dominik\anaconda3
Latest git hash: 5ab4d9e
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\Users\Dominik\DL-Art-School\codes\configuration_gui.py", line 353, in playground_nav_button_event
    self.select_frame_by_name("playground")
  File "C:\Users\Dominik\DL-Art-School\codes\configuration_gui.py", line 332, in select_frame_by_name
    self.playground_api = self.start_tts_api(self.playground_model_path_entry)
  File "C:\Users\Dominik\DL-Art-School\codes\configuration_gui.py", line 656, in start_tts_api
    from inference import save_gen_with_voicefix
  File "C:\Users\Dominik\DL-Art-School\./tortoise-tts-fast/tortoise\inference.py", line 167, in <module>
    vfixer = VoiceFixer()
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\voicefixer\base.py", line 13, in __init__
    self._model = voicefixer_fe(channels=2, sample_rate=44100)
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\voicefixer\restorer\model.py", line 180, in __init__
    self.vocoder = Vocoder(sample_rate=44100)
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\voicefixer\vocoder\base.py", line 19, in __init__
    self._load_pretrain(Config.ckpt)
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\voicefixer\vocoder\base.py", line 26, in _load_pretrain
    checkpoint = load_checkpoint(pth, torch.device("cpu"))
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\voicefixer\vocoder\model\util.py", line 111, in load_checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Dominik\anaconda3\envs\DLAS\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`

**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**, tried a complete clean install however no luck so far.

**Comment by 152334H** [comment]
look for a folder named `.cache/voicefixer`, and delete it. I'm not sure where that is in windows, but it might be in your home user directory.

**Comment by 152334H** [comment]
e.g. `C:\Users\Dominik\.cache\voicefixer`

**Comment by testusersample1** [comment]
> look for a folder named `.cache/voicefixer`, and delete it. I'm not sure where that is in windows, but it might be in your home user directory.

that fixed it thanks, 
For anyone else with this issue, the path would be **C:\Users\[yourusername]\.cache\voicefixer**
