### ISSUE TITLE
Just a question about training models

### ISSUE THREAD

**Issue by demonauthor** [152334H/DL-Art-School#60]
Since training generates huge files, and you can only link one (I'm guessing the last one created) can the rest be deleted to save space? I'm new to this, but I'm assuming each subsequent .pth file is "better" than the one before it?

**Comment by FurkanGozukara** [comment]
> Since training generates huge files, and you can only link one (I'm guessing the last one created) can the rest be deleted to save space? I'm new to this, but I'm assuming each subsequent .pth file is "better" than the one before it?

well it looks like not the case

i am currently doing checkpoint comparison testing and looks like after a point quality degrades

what have you found?
